export const STRINGS = {
  DEFAULT_ERROR_MESSAGE: 'Information not available.',
  READ_MORE: ' Read more',
  HIDE: ' Hide',
  HOME: 'Home',
  MOVIES: 'Movies',
  SERIES: 'Series',
  DETAILS: 'Details',
  CAST: 'Cast',
  PLAY: 'Play',
  ACTION: 'Action',
  COMEDY: 'Comedy',
  DRAMA: 'Drama',
  HORROR: 'Horror',
  ROMANCE: 'Romance',
  TV_MOVIE: 'TV Movie',
  MORE_INFO: 'More info',
  MOST_POPULAR: 'Most popular',
  LESS_POPULAR: 'Less popular',
  TOP_RATED: 'Top rated',
  LOWEST_RATED: 'Lowest rated',
  UPCOMING_RELEASES: 'Upcoming Releases',
  RECENT_RELEASES: 'Recent Releases',
  SIMILAR_MOVIES: 'Similar movies',
  SECTION_TITLES: {
    BIRTHDAY: 'Birthday',
    PLACE_OF_BIRTH: 'Place of birth',
    OCCUPATION: 'Occupation',
    POPULARITY: 'Popularity',
  },
  SECTION_MOVIES_TITLES: {
    STATUS: 'Status',
    RELEASE_DATE: 'Release date',
    DURATION: 'Duration',
    RATING: 'Rating',
  },
};
